//! Persistence.
//!
//! One SQLite database, one writer, many readers. The single writer is not a workaround
//! for SQLite's one-writer limit so much as a way to stop paying for it: ten agents each
//! opening their own write connection would spend their time in lock contention and
//! `BEGIN IMMEDIATE` retries, whereas one actor draining a queue commits batches.
//!
//! Large payloads never enter the database. Whole diffs and terminal transcripts go to
//! content-addressed files and the row keeps a hash, which keeps the file small enough
//! that the pre-migration `VACUUM INTO` backup stays quick.

pub mod blobs;
pub mod boot;
pub mod schema;
mod writer;

use anyhow::{Context, Result};
use rusqlite::{Connection, OpenFlags};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use wkbd_proto::{Event, EventPayload, PendingEvent};

pub use blobs::BlobStore;
pub use boot::{BootGuard, BootOutcome, SafeMode};
pub use writer::{WriteHandle, WriterConfig};

/// Result of opening the store. `degraded` means the database could not be migrated to
/// the version this build expects, so the daemon runs read-only rather than refusing to
/// start. A workbench that will not open cannot be used to recover the work inside it.
pub struct OpenedStore {
    pub store: Store,
    pub degraded: Option<String>,
}

#[derive(Clone)]
pub struct Store {
    inner: Arc<StoreInner>,
}

struct StoreInner {
    db_path: PathBuf,
    write: WriteHandle,
    blobs: BlobStore,
    read_only: bool,
}

fn tune(conn: &Connection) -> Result<()> {
    // WAL lets readers run while the writer commits. Without it every UI read would
    // block behind agent event writes.
    conn.pragma_update(None, "journal_mode", "WAL")?;
    // NORMAL fsyncs at checkpoints rather than at every commit. The exposure is losing
    // the last few committed transactions on power loss or kernel panic; an application
    // crash cannot lose them. For an event log that is regenerated by re-running work,
    // that trade is clearly worth the order-of-magnitude in write throughput.
    conn.pragma_update(None, "synchronous", "NORMAL")?;
    // Connection-scoped, so it has to be set on every connection, not once per database.
    conn.busy_timeout(std::time::Duration::from_millis(5_000))?;
    conn.pragma_update(None, "foreign_keys", "ON")?;
    Ok(())
}

impl Store {
    /// Opens (creating if needed) the database at `dir/workbench.db`.
    ///
    /// Migration failure is reported, not raised: the caller gets a working read-only
    /// store and a reason to show the user.
    pub fn open(dir: &Path) -> Result<OpenedStore> {
        std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
        let db_path = dir.join("workbench.db");

        let mut conn = Connection::open(&db_path)
            .with_context(|| format!("opening {}", db_path.display()))?;
        tune(&conn)?;

        let from = schema::current_version(&conn)?;
        let mut degraded = None;
        if from < schema::latest_version() {
            if from > 0 {
                if let Err(e) = backup_before_migration(&conn, dir, from) {
                    // A failed backup is a reason to refuse to migrate, not a reason to
                    // refuse to run: we can still serve the old schema read-only.
                    degraded = Some(format!("pre-migration backup failed: {e}"));
                }
            }
            if degraded.is_none() {
                if let Err(e) = schema::apply_pending(&mut conn) {
                    degraded = Some(format!("{e}"));
                }
            }
        }

        let read_only = degraded.is_some();
        let blobs = BlobStore::new(dir.join("blobs"))?;
        let write = writer::spawn(db_path.clone(), WriterConfig::default(), read_only)?;

        Ok(OpenedStore {
            store: Store {
                inner: Arc::new(StoreInner { db_path, write, blobs, read_only }),
            },
            degraded,
        })
    }

    pub fn blobs(&self) -> &BlobStore {
        &self.inner.blobs
    }

    pub fn is_read_only(&self) -> bool {
        self.inner.read_only
    }

    /// Opens a fresh read connection. Reads happen on blocking threads; sharing one
    /// connection across them would serialize the UI behind whatever else is reading.
    pub fn read_conn(&self) -> Result<Connection> {
        let conn = Connection::open_with_flags(
            &self.inner.db_path,
            OpenFlags::SQLITE_OPEN_READ_ONLY | OpenFlags::SQLITE_OPEN_NO_MUTEX,
        )?;
        conn.busy_timeout(std::time::Duration::from_millis(5_000))?;
        Ok(conn)
    }

    /// Appends events and returns them with the sequence numbers the database assigned.
    ///
    /// The caller cannot supply `seq`. That is the whole point: an in-memory counter
    /// restarts at zero after a crash, and the resulting primary-key collision on the
    /// next append leaves the application unable to start at all.
    pub async fn append(&self, events: Vec<PendingEvent>) -> Result<Vec<Event>> {
        self.inner.write.append(events).await
    }

    pub async fn append_one(
        &self,
        session_id: impl Into<String>,
        payload: EventPayload,
    ) -> Result<Event> {
        let mut out = self.append(vec![PendingEvent::new(session_id, payload)]).await?;
        out.pop().context("writer returned no event")
    }

    /// Events after `since_seq`, oldest first, plus the current high-water mark.
    ///
    /// Clients resume with the returned mark rather than by checking that sequence
    /// numbers are contiguous. AUTOINCREMENT guarantees monotonicity but not contiguity —
    /// a rolled-back insert leaves a permanent hole — so treating a gap as loss would
    /// make a reconnecting client re-request forever.
    pub fn read_since(
        &self,
        session_id: Option<&str>,
        since_seq: i64,
        limit: usize,
    ) -> Result<(Vec<Event>, i64)> {
        let conn = self.read_conn()?;
        let mut events = Vec::new();

        match session_id {
            Some(sid) => {
                let mut stmt = conn.prepare(
                    "SELECT seq, session_id, at_ms, payload FROM events
                     WHERE session_id = ?1 AND seq > ?2 ORDER BY seq LIMIT ?3",
                )?;
                let rows = stmt.query_map(
                    rusqlite::params![sid, since_seq, limit as i64],
                    row_to_event,
                )?;
                for r in rows {
                    events.push(r??);
                }
            }
            None => {
                let mut stmt = conn.prepare(
                    "SELECT seq, session_id, at_ms, payload FROM events
                     WHERE seq > ?1 ORDER BY seq LIMIT ?2",
                )?;
                let rows =
                    stmt.query_map(rusqlite::params![since_seq, limit as i64], row_to_event)?;
                for r in rows {
                    events.push(r??);
                }
            }
        }

        let high: i64 = conn
            .query_row("SELECT COALESCE(MAX(seq), 0) FROM events", [], |r| r.get(0))
            .unwrap_or(0);
        Ok((events, high))
    }

    pub fn high_water_mark(&self) -> Result<i64> {
        let conn = self.read_conn()?;
        Ok(conn.query_row("SELECT COALESCE(MAX(seq), 0) FROM events", [], |r| r.get(0))?)
    }

    /// Runs a read-only closure on a blocking thread.
    pub async fn read<T, F>(&self, f: F) -> Result<T>
    where
        T: Send + 'static,
        F: FnOnce(&Connection) -> Result<T> + Send + 'static,
    {
        let this = self.clone();
        tokio::task::spawn_blocking(move || {
            let conn = this.read_conn()?;
            f(&conn)
        })
        .await?
    }

    /// Runs a write closure on the writer actor's thread, inside one transaction.
    pub async fn write<T, F>(&self, f: F) -> Result<T>
    where
        T: Send + 'static,
        F: FnOnce(&rusqlite::Transaction) -> Result<T> + Send + 'static,
    {
        self.inner.write.exec(f).await
    }
}

fn row_to_event(row: &rusqlite::Row) -> rusqlite::Result<Result<Event>> {
    let seq: i64 = row.get(0)?;
    let session_id: String = row.get(1)?;
    let at_ms: i64 = row.get(2)?;
    let payload: String = row.get(3)?;
    Ok((|| {
        let payload: EventPayload = serde_json::from_str(&payload)
            .with_context(|| format!("decoding payload of event {seq}"))?;
        Ok(Event { seq, session_id, at_ms, payload })
    })())
}

fn backup_before_migration(conn: &Connection, dir: &Path, from: i64) -> Result<PathBuf> {
    let stamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let backups = dir.join("backups");
    std::fs::create_dir_all(&backups)?;
    let target = backups.join(format!("workbench-v{from}-{stamp}.db"));
    // VACUUM INTO is consistent against a live database and does not need the backup API
    // or a file copy, both of which can capture a torn WAL.
    conn.execute(&format!("VACUUM INTO '{}'", target.display()), [])?;
    tracing::info!(path = %target.display(), "wrote pre-migration backup");
    Ok(target)
}

pub fn now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests;
