//! Deciding whether a test identifier names something that exists.
//!
//! # Why not ask the test runner
//!
//! Because asking means building. `cargo test -- --list`, `pytest --collect-only` and `go test
//! -list` all compile the project first, they are all spelled differently, and a planner waiting
//! on a cold Rust build is a planner that has stopped being interactive. It is also the wrong
//! trade for what this decides: the answer feeds one validation rule, and getting it slightly
//! wrong costs a redraft, while taking two minutes to get it exactly right costs every draft.
//!
//! # What this does instead
//!
//! Scans the repository's own text for the identifier. Not a parse and not a claim about the
//! test runner's view of the world: a claim about whether the name the planner used appears
//! anywhere in the project.
//!
//! The identifier is matched by its last segment, because runners qualify names and source files
//! do not. `cargo test` prints `config::loads` for a function written `fn loads()` inside `mod
//! config`, so a literal search for the whole identifier finds nothing and rejects a real test.
//! Splitting on `::`, `.`, `#` and `/` and looking for `loads` finds it, and covers Python's
//! `tests/test_config.py::test_loads`, Java's `ConfigTest#loads` and Go's `TestLoads` with the
//! same rule.
//!
//! # Which way it is allowed to be wrong
//!
//! Towards accepting. A name that appears in a comment or an unrelated variable is accepted, and
//! the task fails at acceptance instead — which is what happens today for every identifier. A
//! name generated by a macro and never written literally would be rejected, and that is the
//! failure that matters, because the planner would be sent back to redraft a graph that was
//! correct. So the match is deliberately loose, and a scan that cannot complete accepts
//! everything rather than blocking a run on its own failure.

use std::collections::HashSet;
use std::io::Read;
use std::path::Path;
use wkbd_orch::graph::TestInventory;

/// Bytes of any one file that are searched. A minified bundle or a fixture dump contains every
/// short string by accident, and reading it costs more than the answer is worth.
const MAX_FILE_BYTES: usize = 1024 * 1024;

/// Files searched, at most. A bound on the time a draft can wait.
const MAX_FILES: usize = 5_000;

/// Shortest last segment worth searching for.
///
/// A two-character name matches everything, so an identifier that reduces to one is treated as
/// unverifiable and accepted rather than confirmed against noise.
const MIN_SEGMENT: usize = 3;

pub struct RepoTests {
    /// Every word-like token found in the project's text, lowercased.
    ///
    /// Tokens rather than the raw text, so a lookup is a hash probe instead of a scan per
    /// identifier, and so `loads` does not match `preloads`. Substring matching sounds more
    /// forgiving and is the wrong kind: it accepts almost anything, which turns the rule back
    /// into the no-op it replaced.
    tokens: HashSet<String>,
    /// True when the scan hit a limit or could not read the tree. Everything is accepted then.
    partial: bool,
}

impl RepoTests {
    pub fn scan(root: &Path) -> RepoTests {
        let mut tokens = HashSet::new();
        let mut files = 0usize;
        let mut partial = false;

        let walker = ignore::WalkBuilder::new(root)
            .hidden(true)
            .follow_links(false)
            .git_ignore(true)
            .git_global(false)
            .require_git(false)
            .max_depth(Some(12))
            .build();

        for entry in walker.flatten() {
            if !entry.file_type().is_some_and(|t| t.is_file()) {
                continue;
            }
            files += 1;
            if files > MAX_FILES {
                partial = true;
                break;
            }
            let Ok(mut file) = std::fs::File::open(entry.path()) else { continue };
            let mut buf = Vec::new();
            if file.by_ref().take(MAX_FILE_BYTES as u64).read_to_end(&mut buf).is_err() {
                continue;
            }
            // Binary is skipped rather than lossily converted: a lossy conversion of a
            // compiled artifact produces tokens that exist nowhere in the source.
            let Ok(text) = String::from_utf8(buf) else { continue };

            for token in text.split(|c: char| !c.is_alphanumeric() && c != '_') {
                if token.len() >= MIN_SEGMENT {
                    tokens.insert(token.to_ascii_lowercase());
                }
            }
        }

        if tokens.is_empty() {
            // An empty repository and an unreadable one look the same from here, and the
            // difference decides whether every identifier is rejected or none is.
            partial = true;
        }

        RepoTests { tokens, partial }
    }

    /// An inventory that knows nothing and therefore refuses nothing.
    ///
    /// For the case where the scan itself could not be run. The validator must never fail a plan
    /// because the thing checking it fell over.
    pub fn unavailable() -> RepoTests {
        RepoTests { tokens: HashSet::new(), partial: true }
    }

    /// True when the scan was cut short, in which case every identifier is accepted.
    pub fn is_partial(&self) -> bool {
        self.partial
    }

    pub fn token_count(&self) -> usize {
        self.tokens.len()
    }
}

/// The part of a test identifier that a source file is likely to contain verbatim.
fn last_segment(test_id: &str) -> &str {
    test_id
        .rsplit(|c| c == ':' || c == '.' || c == '#' || c == '/')
        .find(|s| !s.is_empty())
        .unwrap_or(test_id)
}

impl TestInventory for RepoTests {
    fn contains(&self, test_id: &str) -> bool {
        if self.partial {
            return true;
        }
        let segment = last_segment(test_id).to_ascii_lowercase();
        if segment.len() < MIN_SEGMENT {
            return true;
        }
        self.tokens.contains(&segment)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("src")).unwrap();
        std::fs::write(
            dir.path().join("src/config.rs"),
            "mod config {\n  #[test]\n  fn loads() {}\n}\n",
        )
        .unwrap();
        dir
    }

    /// The case that makes a literal search wrong. `cargo test` prints the qualified name; the
    /// file contains only the function.
    #[test]
    fn a_qualified_identifier_matches_the_function_in_the_source() {
        let inv = RepoTests::scan(fixture().path());
        assert!(!inv.is_partial());
        assert!(inv.contains("config::loads"));
        assert!(inv.contains("tests/test_config.py::loads"));
        assert!(inv.contains("ConfigTest#loads"));
    }

    #[test]
    fn a_name_nobody_wrote_is_not_found() {
        let inv = RepoTests::scan(fixture().path());
        assert!(!inv.contains("config::reloads_from_disk"));
        assert!(!inv.contains("invented_guard"));
    }

    /// Whole tokens, not substrings, and the direction that matters is a real name sitting
    /// inside a longer one.
    ///
    /// The repository has `cache_warm` and does not have `warm`. Substring matching says it has
    /// both, which is how a rule that looks stricter than "accept everything" turns back into it.
    #[test]
    fn a_name_inside_a_longer_one_is_not_a_match() {
        let dir = fixture();
        std::fs::write(dir.path().join("src/cache.rs"), "fn cache_warm() {}\n").unwrap();
        let inv = RepoTests::scan(dir.path());

        assert!(inv.contains("cache_warm"));
        assert!(!inv.contains("warm"), "a fragment of a name is not the name");
        assert!(!inv.contains("cache_warm_twice"));
    }

    /// Failing towards acceptance. A scan that could not run must not block a valid plan.
    #[test]
    fn an_unreadable_tree_accepts_everything() {
        let empty = tempfile::tempdir().unwrap();
        let inv = RepoTests::scan(empty.path());
        assert!(inv.is_partial());
        assert!(inv.contains("anything::at::all"));

        let missing = RepoTests::scan(std::path::Path::new("/nonexistent-for-this-test"));
        assert!(missing.contains("anything"));
    }

    #[test]
    fn a_segment_too_short_to_mean_anything_is_accepted() {
        let inv = RepoTests::scan(fixture().path());
        assert!(inv.contains("a::b"));
    }

    /// Ignored files are not scanned, so a name that exists only in a build artifact does not
    /// vouch for a test.
    #[test]
    fn generated_output_does_not_vouch_for_a_test() {
        let dir = fixture();
        std::fs::write(dir.path().join(".gitignore"), "target/\n").unwrap();
        std::fs::create_dir_all(dir.path().join("target")).unwrap();
        std::fs::write(dir.path().join("target/out.txt"), "generated_only_name").unwrap();

        let inv = RepoTests::scan(dir.path());
        assert!(!inv.contains("generated_only_name"));
    }
}
